### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by andypeal** [ds4owd-001/md-02-assignments-andypeal#1]
@larnsce @mianzg @sskorik01 - have completed module 2 assignments (tasks 1 through 11).
Thanks
Andy

**Comment by larnsce** [comment]
Thank you for working through the assignment, @andypeal. Can you confirm that you committed and pushed all changes to the md-02a-data-visualization.qmd file on posit.cloud? Your GitHub repository does not reflect your work, yet.

**Comment by andypeal** [comment]
@larnsce - OK thanks - I forgot the push step - think I have pushed changes now?

**Comment by larnsce** [comment]
Yes, you have. Great job! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-02-assignments-andypeal/commit/772b6bc58b57e8a9fead7673484f25fb90847dc7

On each line, one can add comments. A bit like you would do in MS Word with comments and track changes. 

I will close the issue for you now.
